name = "ghibli-ai"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.production]
pages_build_output_dir = "out"

[[build.production.d1_databases]]
binding = "DB"
database_name = "ghibli-ai-db"
database_id = "ghibli-ai-production"

[env.production]
routes = [
  { pattern = "ghibli-ai.pages.dev", zone_name = "pages.dev" }
]

[site]
bucket = "out" 